### ISSUE TITLE
Releases in GitHub

### ISSUE THREAD

**Issue by pafnuty** [qandak/sumcalc#1]
Hi @qandak!
Huge thanks for your program, this is exactly what I was looking for!
May you can create release in github? This will make it easier to download a program.
Thanks!

**Comment by qandak** [comment]
Hi @pafnuty!
Thank you for your encouragement!
Just to clarify. Do you want to download the source from releases, or the bundle for Windows which is already on Sourceforge?

**Comment by pafnuty** [comment]
@qandak I would like to have the ability to download ready-to-run bundle which is already on Sourceforge.
Also, after create release on https://github.com/qandak/sumcalc/releases it will be created from current master and you can attach bundle for this release manually.

**Comment by qandak** [comment]
@pafnuty, done.
I hope this is what you expected.

**Comment by pafnuty** [comment]
@qandak yes that's it!
